version: "3.9"

services:
  futsal_gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env

  futsal_nginx:
    image: nginx:latest
    volumes:
      - static_volume:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - futsal_gunicorn

volumes:
  static_volume:

